### ISSUE TITLE
Advice on CAUSE data reliability?

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/GALEX_Boyajian#1]
Is there any reason to *not* trust the flux (and errors) from the CAUSE catalog of the [Kepler field](https://arxiv.org/abs/1510.00748)?

The table on Vizier gives a fairly precise NUV magnitude for [this star](http://vizier.cfa.harvard.edu/viz-bin/VizieR-5?-ref=VIZ5925faa6255b&-out.add=.&-source=J/ApJ/813/100/table4&recno=660470).

cc: @cmillion, @daveonebillion, @scfleming, @parkus, @emamajek
+ others I should reach out to?? I couldn't find Manuel Olmedo on GitHub

**Comment by jradavenport** [comment]
also cc: @bshiao

**Comment by cmillion** [comment]
I think that Olmedo, et al. did a thorough job of cleaning up the CAUSE data. And I think it's probably good. But I would also not necessarily trust it implicitly just because scan mode is an "all bets are off" situation in my mind. And the behavior of this star is sufficiently weird and the "fit" sufficiently compelling that I'd be worried about confirmation bias. So maybe trust but verify. Since this was also observed during the "normal" mission, I would check that nearby stars do not show similar dramatic changes in photometry before / after CAUSE.

I've sent Manuel an email alerting him to this thread.

**Comment by jradavenport** [comment]
"Trust but verify", wise words! Thanks for pinging Manuel, and for being **amazingly helpful and patient** with this (and other ideas/threads) Scott!!

If a paper comes out of this (see #3) you are definitely a co-author for your efforts!

**Comment by scfleming** [comment]
To be clear, some of my comments via Twitter were a combination of mine and Chase's from a discussion we had about this, to make sure I don't take credit for all the suggestions I passed along.

**Comment by jradavenport** [comment]
Ack, sorry, my brain cross-wired Chase's comment here... read it as Scott! Sorry!!!!!

Scott, comment holds: thank you for your continued patience and help w/ all things GALEX

Chase: thank you for your help here!! I happily would welcome co-authorship from you both!

**Comment by emamajek** [comment]
Manual spent a year reducing and analyzing the CAUSE GALEX data and writing
up the paper. This is a fairly bright and hot star, and there were 1414
seconds of GALEX exposure to work with, and the background level looks very
well-constrained - so it is unsurprising that it is a high S/N detection.
You might want to ask Manual for the time-series photometry as well. He's
knee-deep in a follow-up paper studying the UV excesses and trends of stars
in the Kepler field (Miguel Chavez Dagostino at INAOE in Puebla is advising
Manual on the rest of his thesis; he did the CAUSE survey while visiting U.
Rochester for a year).

cheers,
Eric

**Comment by jradavenport** [comment]
Excellent, thank you for chiming in so quickly, Eric @emamajek!

**Comment by cosmocaos** [comment]
Hi everyone, 
Sure you can trust the GCK catalog. As in any big catalog or survey there is a fraction of objects that could be affected by artifacts, saturation, false positive etc.. The considerations to clean the GCK catalog for spurious/affected detections consisted of filtering by geometric characteristics of the fitted apertures, these were properly set to get rid of nearly all spurious/affected detections while not loosing to many good sources.    
For analysis involving large samples you will have some spurious detections, that you can diminish using only high SNR sources.  
In the case of small samples, as Chase said, you can verify, in case of bad luck and your source is in a region affected by an artifact. 
I attach the coadded tile of GCK data, indicating KIC8462852 with a red circle. In the zoom out image you can see there are artifacts, but in the zoom in image, you can see KIC8462852 is free of artifacts. 
I'll be happy to further help you regarding the GCK data/catalog. 

Chase: Thanks for the notice about this thread.
![kic8462852_1](https://cloud.githubusercontent.com/assets/16109293/26612042/dda0537e-4577-11e7-9835-5b2be33f9a2d.png)
![kic8462852_2](https://cloud.githubusercontent.com/assets/16109293/26612043/dda0ec9e-4577-11e7-8c00-ee2d6fddbce4.png)
![kic8462852_3](https://cloud.githubusercontent.com/assets/16109293/26612044/dda9ac8a-4577-11e7-9600-8829fc27038d.png)
