### ISSUE TITLE
Similarly, what does WISE have to say about all this?

### ISSUE THREAD

**Issue by jradavenport** [jradavenport/GALEX_Boyajian#4]
The other mission I am very familiar with is WISE, has *similar* time coverage...

With NeoWISE, AllWISE, etc, should have visits spanning several years in W1 and W2 (3.4 and 4.5 micron), with several day clumps of observations, and visits spaced ever ~6mo for a few years. The star is ~10th mag in IR, perfect for this instrument! If long-term fading is due to dust, should see very little change. If fading is due to more solid objects, should see comparable dimming as in Kepler and GALEX (few %).

@RileyWClarke is working on this stat!

- [x] pull all Single Exposure data down
- [x] look at short (days) and long (full baseline, years) timescale W1 light curve
- [x] also W2
- [x] also W1-W2

**Comment by jradavenport** [comment]
@benmontet did you all look at this?

**Comment by jradavenport** [comment]
@kevincovey I think first sparked this idea in our chat last week

**Comment by benmontet** [comment]
We haven't looked in terms of time series! The Marengo et al paper in ApJL says the following:

The WISE observations of KIC 8462852, however, were
restricted to Kepler Q5 nine months before the first dimming
event in 2011 March (Q8)....
...The star was in fact observed by the IRAC camera (Fazio
et al. 2004) on board the Spitzer Space Telescope (Werner
et al. 2004) in early 2015 as part of the SpiKeS program aimed
to map the entire Kepler field.

We took them at face value, but if there are more beyond Q12 then they would of course be useful! The WISE and Spitzer bandpasses look just different enough to not be helpful in ~0.02 mag effects.

I wonder if anyone has looked at all the vizier data to see if there are any 0.1mag anomalous observations in any bandpass at any time.

**Comment by jradavenport** [comment]
Cool! @RileyWClarke & I will report back in a day or two with some IR light curves!

Now kinda in love with the idea of GALEX + WISE for this target, provide 2 anchors to the time evolution!

**Comment by benmontet** [comment]
Looking forward to seeing what you two come up with! A GALEX-WISE color time series could be powerful. (How's that for a sentence that would only make sense to astronomers)

**Comment by benmontet** [comment]
Relevant to your interests, this dropped today: http://wise2.ipac.caltech.edu/docs/release/neowise/

**Comment by jradavenport** [comment]
Awesome, hopefully @RileyWClarke can get new light curves from [here](http://irsa.ipac.caltech.edu/Missions/wise.html)

**Comment by jradavenport** [comment]
@RileyWClarke got things started last week, and today I [forked his repo](https://github.com/jradavenport/WISE_Boyajian) and played with it more...

The WISE flux in W1 (and W2) is basically flat... 
![w1_relflux](https://user-images.githubusercontent.com/3179868/26864676-36eacde2-4b0e-11e7-9266-3b5538007d16.png)
though there is a *small* fading between the first 2 visits. If we were careful (thinking aloud here) we could assume the Kepler flux is "true", and explore (MCMC?) the *R_V* dust parameter that would give the measured GALEX and WISE changes that overlap the Kepler data. I think this is a very good approach, and I should start working on it in the GALEX repo


On the *shorter* timescale there isn't anything definitive to say. The "dips" in W1 are interesting, but for the one visit that has Kepler overlap (lc_2), Kepler doesn't show any such dip... so these may be WISE errors? Note: they all have W1 flag `ph_qual = 'A'`, so not a bad datapoint on the surface.
![lc_2](https://user-images.githubusercontent.com/3179868/26864899-3ff4f484-4b0f-11e7-9c3f-438479513495.png)
